services:
  ev-api:
    container_name: ev-api
    image: ${REGISTRY}/ev-api:latest
    restart: always
    build: 
      context: ..
      dockerfile: EV_Driver/Dockerfile
    networks:
      - ev-network

networks:
  ev-network:
    name: ev-network
    external: true